name: Build Kivy APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-11-jdk-headless libncursesw6 libtool pkg-config autoconf automake libffi-dev libssl-dev

      - name: Install buildozer
        run: pip install buildozer

      - name: Compile APK
        run: buildozer android debug

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: output-apk
          path: bin/*.apk
